export const aiModels = [
  'google/gemini-2.0-flash-thinking-exp:free',
  'google/gemini-2.0-flash-exp:free',
  'openrouter/quasar-alpha',
  'google/gemini-2.5-pro-exp-03-25:free',
  'google/gemini-flash-1.5-8b-exp',
  'meta-llama/llama-4-scout:free',
  'meta-llama/llama-4-maverick:free',
  'deepseek/deepseek-r1-zero:free',
  'deepseek/deepseek-r1:free',
  'deepseek/deepseek-v3-base:free',
  'deepseek/deepseek-chat-v3-0324:free',
  'google/gemma-3-4b-it:free',
  'google/gemma-3-12b-it:free',
  'nousresearch/deephermes-3-llama-3-8b-preview:free',
  'qwen/qwen2.5-vl-72b-instruct:free',
  'deepseek/deepseek-chat:free',
  'nvidia/llama-3.1-nemotron-70b-instruct:free',
  'meta-llama/llama-3.2-1b-instruct:free',
  'meta-llama/llama-3.2-11b-vision-instruct:free',
  'meta-llama/llama-3.1-8b-instruct:free',
  'deepseek/deepseek-r1-distill-llama-70b:free',
  'mistralai/mistral-nemo:free',
  'mistralai/mistral-small-3.1-24b-instruct:free',
  'google/gemma-3-27b-it:free',
  'qwen/qwen2.5-vl-3b-instruct:free',
  'deepseek/deepseek-r1-distill-qwen-14b:free',
  'qwen/qwen-2.5-vl-7b-instruct:free',
  'google/learnlm-1.5-pro-experimental:free',
  'qwen/qwq-32b:free',
  'google/gemini-2.0-flash-thinking-exp-1219:free',
  'bytedance-research/ui-tars-72b:free',
  'featherless/qwerky-72b:free',
  'open-r1/olympiccoder-7b:free',
  'open-r1/olympiccoder-32b:free',
  'google/gemma-3-1b-it:free',
  'rekaai/reka-flash-3:free',
  'cognitivecomputations/dolphin3.0-r1-mistral-24b:free',
  'cognitivecomputations/dolphin3.0-mistral-24b:free',
  'mistralai/mistral-small-24b-instruct-2501:free',
  'qwen/qwen-2.5-coder-32b-instruct:free',
  'qwen/qwen-2.5-7b-instruct:free',
  'qwen/qwen-2.5-72b-instruct:free',
  'meta-llama/llama-3.2-3b-instruct:free',
  'qwen/qwq-32b-preview:free',
  'deepseek/deepseek-r1-distill-qwen-32b:free',
  'qwen/qwen2.5-vl-32b-instruct:free',
  'moonshotai/moonlight-16b-a3b-instruct:free',
  'google/gemma-2-9b-it:free',
  'mistralai/mistral-7b-instruct:free',
  'microsoft/phi-3-mini-128k-instruct:free',
  'microsoft/phi-3-medium-128k-instruct:free',
  'openchat/openchat-7b:free',
  'meta-llama/llama-3.3-70b-instruct:free',
  'allenai/molmo-7b-d:free',
  'sophosympatheia/rogue-rose-103b-v0.2:free',
  'undi95/toppy-m-7b:free',
  'huggingfaceh4/zephyr-7b-beta:free',
];

export const aiModelsSystemGeneriqueAsk =
  'response with 40 words max, use all time comic style and be very suitable plz dont forget you will change the person very quick,speak in the possessive pronoun and in the first person, you can use emojy end decorator';

export const aiModelsSystemUniqueAsk = [
  {
    id: 1,
    text: 'Your are Beluga the most comic person in the word you need to help person to be cool.',
  },
  {
    id: 2,
    text: 'Your are Belu Mom the most comic person in the word you need to help person to be cool.',
  },
  {
    id: 3,
    name: 'Your are Hecker the most comic person in the word you need to help person to be cool.',
  },
  {
    id: 4,
    name: 'Your are Jb X White the most comic person in the word you need to help person to be cool.',
  },
  {
    id: 5,
    name: 'Your are Lesterman the most comic person in the word you need to help person to be cool.',
  },
  {
    id: 6,
    name: 'Your are Pepper High Quality the most comic person in the word you need to help person to be cool.',
  },
  {
    id: 7,
    name: 'Scemer Your are Lesterman the most comic person in the word you need to help person to be cool.',
  },
  {
    id: 8,
    name: 'Your are Skittle the most comic person in the word you need to help person to be cool.',
  },
  {
    id: 9,
    name: 'Your are Voice the most comic person in the word you need to help person to be cool.',
  },
  {
    id: 10,
    name: 'Your are Walt the most comic person in the word you need to help person to be cool.',
  },
];
